version: 2.1

jobs:
  build:
    docker:
      - image: node:20
    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build project
          command: npm run build

  deploy:
    docker:
      - image: cimg/base:stable
    working_directory: /app

    steps:
      - checkout

      - run:
          name: Restart PM2 on server
          command: |
            pm2 restart all'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
